#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from src.chessbot.secrets import token_from_keyring


KEY_SPECS: tuple[tuple[str, str, str], ...] = (
    ("RUNPOD_API_KEY", "runpod", "RUNPOD_API_KEY"),
    ("HF_READ_TOKEN", "huggingface", "codex_hf_read_token"),
    ("HF_WRITE_TOKEN", "huggingface", "codex_hf_write_token"),
    ("LICHESS_BOT_TOKEN", "lichess", "lichess_api_token"),
)


def _quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _collect_keyring_values() -> tuple[dict[str, str], list[str]]:
    values: dict[str, str] = {}
    missing: list[str] = []
    for env_key, service, username in KEY_SPECS:
        token = token_from_keyring(service, username)
        if token:
            values[env_key] = token
        else:
            values[env_key] = ""
            missing.append(f"{env_key} (keyring: {service}/{username})")
    return values, missing


def _render_env_file(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/populate_env_from_keyring.py",
        "# Secrets-only file: do not commit.",
        "# HF_WRITE_TOKEN is publish-only; do not use this token on cloud training pods.",
        "",
    ]
    for env_key, _, _ in KEY_SPECS:
        lines.append(f"{env_key}={_quote_env_value(values.get(env_key, ''))}")
    lines.append("")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Populate .env from canonical keyring entries.")
    p.add_argument("--output", default=".env", help="Path to write the dotenv file (default: .env)")
    p.add_argument(
        "--allow-missing",
        action="store_true",
        help="Write empty values for missing entries instead of failing.",
    )
    return p


def main() -> int:
    args = build_parser().parse_args()
    values, missing = _collect_keyring_values()
    if missing and not args.allow_missing:
        print("Missing required keyring entries:")
        for item in missing:
            print(f"- {item}")
        print("Use --allow-missing to write empty placeholders.")
        return 2

    out_path = Path(args.output).expanduser()
    rendered = _render_env_file(values)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {out_path} with {len(KEY_SPECS)} keys.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
